services:
  - type: web
    name: echofy-capital-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn_config.py app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SESSION_COOKIE_SECURE
        value: true
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: echofy-capital-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: echofy-capital-db
    plan: free
    databaseName: fund_manager
    user: fund_manager_user
