name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m py_compile app.py
        echo "✅ App compiles successfully"
        
    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        echo "🚀 Deploying to Render..."
        # The actual deployment will be handled by Render's auto-deploy
        # when code is pushed to the main branch
        echo "✅ Code pushed successfully. Render will auto-deploy."
        
    - name: Notify deployment status
      run: |
        echo "🎉 Deployment workflow completed!"
        echo "Check your Render dashboard for deployment status."
